# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'My Azure Resource Manager'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
     $subId = az account show --query id --output tsv
     Write-Host "This is my subscriptiojn id: " $subId
     Write-Host "This is my SP": $servicePrincipalId
     Write-Host "This is my SPKey: " $servicePrincipalKey
     Write-Host "This is my tenantID: " $tenantId
    addSpnToEnvironment: true
  continueOnError: true

# - task: PowerShell@2
#   name: 'UseVal2' 
#   inputs:
#     targetType: 'inline'
#     script: 'Write-Host The value of setvalue is $(SetVal2.setvalue)'
