# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  outputVar: 
steps:
- task: PowerShell@2
  displayName: Execute PowerShell script
  inputs:
    targetType: 'inline'
    script: az login
- task: PowerShell@2
  displayName: Execute PowerShell script
  inputs:
    targetType: 'inline'
    script: $outputVar = az account show --query id --output tsv
- task: PowerShell@2
  displayName: Execute PowerShell script
  inputs:
    targetType: 'inline'
    script: |
      Write-Host $outputVariable

